config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :create, :show] do
    get :all_boards, on: :collection
  end
  root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  default_scope { order(created_at: :desc) }

  has_many :mines
  validates :name, :width, :height, :email, :number_of_mines, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :max_number_of_mines
  before_create :build_mines

  private

  def max_number_of_mines
    return if width.nil? || height.nil? || number_of_mines.nil?

    errors.add(:number_of_mines, "too many mines") if (width * height) < number_of_mines
  end

  def build_mines
    boms = generate_random_mine
    boms.each do |mine|
      mines.build(x: mine.first, y: mine.last)
    end
  end

  def generate_random_mine
    boms = []
    while boms.size <= number_of_mines
      col = rand(1..width)
      row = rand(1..height)
      boms << [col, row]
      boms.uniq(&:first)
    end
    boms
  end
end

# == Schema Information
#
# Table name: games
#
#  id          :bigint           not null, primary key
#  name        :string
#  width       :integer
#  height      :integer
#  email       :string
#  number_of_mines       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/models/mine.rb
class Mine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :load_game, only: %i[show]

  def index
    @games = Game.select('id, name, email, created_at').limit(10)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.js
      else
        format.html { flash[:alert] = @game.errors.full_messages.to_sentence }
        format.js
      end
    end
  end

  def show; end

  def all_boards
    @games = Game.select('id, name, email, created_at')
  end

  private

  def game_params
    params.require(:game).permit(:name, :width, :height, :email, :number_of_mines)
  end

  def load_game
    @game = Game.find_by_id(params[:id])
    return if @game.present?

    flash[:alert] = "Game doesn't exists."
    redirect_to games_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def generate_board(game)
    mines = game.mines.collect{|m| [m.x,m.y]}
    cols = [*1..game.width]
    rows = [*1..game.height]
    rows.map do |row|
      tag.div class: "box-tile" do
        cols.map do |col|
          tag.div class: "d-inline-flex flex-nowrap me-2 tile" do
            if mines.include?([col,row])
              tag.i class: "fas fa-bomb"
            else
              tag.i class: "fas fa-square"
            end
          end
        end.join.html_safe
      end
    end.join
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_boards.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each_with_index do |game, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= link_to game&.name, game, class: 'btn btn-link' %> <%=  %></td>
        <td><%= game&.email %></td>
        <td><%= game&.created_at&.strftime('%d/%m/%Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_form.html.erb
<%= simple_form_for game, remote: true do |f| %>
  <div class="modal-body">
    <%= f.input :email, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    <%= f.input :name, wrapper_html: { class: 'mb-3' }, label: "Board Name", label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    <%= f.input :width, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    <%= f.input :height, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    <%= f.input :number_of_mines, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.button :submit, "Save Board", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/games/all_boards.html.erb
<h3 class="mt-3">All generated boards</h3>
<%= render partial: "boards" %>

app/views/games/create.js.erb
<% if @game.errors.present? %>
  $("#board-form").html("<%= j render('form', game: @game) %>")
<% else %>
  window.location.replace("<%= game_path(@game) %>")
<% end %>

app/views/games/index.html.erb
<h1 class="display-6 fw-bold">Minesweeper Game</h1>
<div class="text-end">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalBoard">
    Generate Board
  </button>
</div>
<h3 class="mt-3">Most Recently Generated Boards</h3>
<%= render partial: "boards" %>
<%= link_to "view all generated boards", all_boards_games_path, class: 'btn btn-primary' %>

<!-- Modal -->
<div class="modal fade" id="modalBoard" tabindex="-1" aria-labelledby="modalBoard" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Create Board</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="board-form">
      <%= render "form", game: Game.new %>
    </div>
  </div>
</div>

<%= content_for :javascripts do %>
<script>
  $(document).ready(function(){
    $('#modalBoard').modal('show');
  });
</script>
<% end %>

app/views/games/new.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.input :email, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
  <%= f.input :name, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
  <%= f.input :width, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
  <%= f.input :height, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
  <%= f.input :number_of_mines, wrapper_html: { class: 'mb-3' }, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
  <%= f.button :submit, "Save game", class: "btn btn-primary"  %>
<% end %>

app/views/games/show.html.erb
<div class="text-center overflow-auto">
  <h2>Board  <%= @game.name%> </h2>
  <span>Creator <%= @game.email%> </span>
  <%= raw generate_board(@game)%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript">
      // Notice how this gets configured before we load Font Awesome
      window.FontAwesomeConfig = { autoReplaceSvg: false }
    </script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Minesweeper</a>
        </div>
      </nav>

      <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-2">
          <% flash.each do |type, msg| %>
            <div class="alert alert-<%= type == 'notice' ? 'info' : 'danger' %>">
              <%= msg %>
            </div>
          <% end %>

          <%= yield %>
        </div>
      </div>
    </div>
    <%= yield :javascripts %>
  </body>
</html>